# Generated by Django 4.0.2 on 2022-06-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import eggslist.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="slug")),
            ],
            options={"verbose_name": "blog category", "verbose_name_plural": "blog categories"},
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="title")),
                ("slug", models.SlugField(max_length=512, unique=True, verbose_name="slug")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="", verbose_name="image"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="date created"),
                ),
                ("body", models.TextField(verbose_name="body")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogs.blogcategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={"verbose_name": "blog article", "verbose_name_plural": "blog articles"},
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
    ]
