# Generated by Django 4.0.2 on 2022-06-23 08:54

from django.db import migrations, models

import eggslist.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', eggslist.users.managers.EggslistUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='is email verified'),
        ),
    ]
