# Generated by Django 4.0.2 on 2022-08-29 22:02

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars', verbose_name='avatar'),
        ),
        migrations.CreateModel(
            name='VerifiedSellerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to='seller_verifications', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is_approved')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'verified seller application',
                'verbose_name_plural': 'verified seller application',
            },
        ),
    ]
