# Generated by Django 4.0.2 on 2022-09-06 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_verifiedsellerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='following_user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user favorite farm',
                'verbose_name_plural': 'user favorite farms',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddConstraint(
            model_name='userfavoritefarm',
            constraint=models.UniqueConstraint(fields=('user', 'following_user'), name='favorite_farm_unique_constraint'),
        ),
    ]
