# Generated by Django 4.0.2 on 2022-09-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userfavoritefarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_seller_pending',
            field=models.BooleanField(default=False, verbose_name='is verified seller pending'),
        ),
    ]
