# Generated by Django 4.0.2 on 2022-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_randomize_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIPLocationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=128, verbose_name='ip address')),
                ('determined_city', models.CharField(max_length=128, null=True, verbose_name='determined city')),
            ],
        ),
    ]
