# Generated by Django 4.0.2 on 2022-11-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useriplocationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStripeConnection',
            fields=[
                ('stripe_account', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='stripe account')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('is_onboarding_completed', models.BooleanField(default=False, verbose_name='is onboarding completed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_connection', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user stripe connection',
                'verbose_name_plural': 'user stripe connections',
                'ordering': ('-created_at',),
            },
        ),
    ]
