# Generated by Django 4.0.2 on 2022-04-29 18:49

import django.db.models.deletion
from django.db import migrations, models

import eggslist.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationCity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="slug")),
            ],
            options={"verbose_name": "location city", "verbose_name_plural": "location cities"},
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LocationCountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "location country",
                "verbose_name_plural": "location countries",
            },
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LocationZipCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="slug")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zip_codes",
                        to="site_configuration.locationcity",
                        verbose_name="city",
                    ),
                ),
            ],
            options={
                "verbose_name": "location zip code",
                "verbose_name_plural": "location zip codes",
            },
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LocationState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="slug")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="site_configuration.locationcountry",
                        verbose_name="country",
                    ),
                ),
            ],
            options={"verbose_name": "location state", "verbose_name_plural": "location states"},
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="locationcity",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="site_configuration.locationstate",
                verbose_name="state",
            ),
        ),
    ]
