# Generated by Django 4.0.2 on 2022-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0002_add_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=32, verbose_name='author name')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
            },
        ),
    ]
