# Generated by Django 4.0.2 on 2022-09-27 22:04

from django.db import migrations, models


def set_default_system_name(apps, schema_editor):
    LocationZipCode = apps.get_model("site_configuration", "LocationZipCode")
    LocationZipCode.objects.update(system_name=models.F("slug"))
    LocationZipCode.objects.update(slug=models.F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ("site_configuration", "0005_leading_zero_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationzipcode",
            name="system_name",
            field=models.CharField(default="", max_length=64, verbose_name="system name"),
        ),
        migrations.RunPython(set_default_system_name, migrations.RunPython.noop),
    ]
