# Generated by Django 4.0.2 on 2022-10-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0007_locationcity_location_locationstate_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('position',), 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('position',), 'verbose_name': 'team member', 'verbose_name_plural': 'team members'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('position',), 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.AddField(
            model_name='faq',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
