# Generated by Django 4.0.2 on 2022-04-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import eggslist.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="slug")),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
            ],
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="slug")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="store.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={"verbose_name": "subcategory", "verbose_name_plural": "subcategories"},
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="title")),
                ("slug", models.SlugField(max_length=512, unique=True, verbose_name="slug")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="", verbose_name="image"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, verbose_name="price"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="date created"),
                ),
                ("allow_pickup", models.BooleanField(default=True, verbose_name="allow pickup")),
                (
                    "allow_delivery",
                    models.BooleanField(default=False, verbose_name="allow delivery"),
                ),
                ("is_banned", models.BooleanField(default=False, verbose_name="is banned")),
                (
                    "seller_status",
                    models.CharField(
                        choices=[
                            ("archived", "archived"),
                            ("out_of_stock", "out of stock"),
                            ("active", "active"),
                        ],
                        default="active",
                        max_length=32,
                        verbose_name="seller status",
                    ),
                ),
                (
                    "engagement_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nubmer of clicks on `Contact` button in the product page",
                        verbose_name="engagement count",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="seller",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.subcategory",
                        verbose_name="subcategory",
                    ),
                ),
            ],
            options={"verbose_name": "product article", "verbose_name_plural": "product articles"},
            bases=(eggslist.utils.models._SlugModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_subcategory"
            ),
        ),
    ]
