# Generated by Django 4.0.2 on 2022-08-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userviewtimestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productarticle',
            name='seller_status',
        ),
        migrations.AddField(
            model_name='productarticle',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
        migrations.AddField(
            model_name='productarticle',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='is out of stock'),
        ),
    ]
