# Generated by Django 4.0.2 on 2022-09-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productarticle_seller_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userviewtimestamp',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='user_product_unique_constraint'),
        ),
    ]
