# Generated by Django 4.0.2 on 2022-11-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_transaction_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='application_fee',
            field=models.IntegerField(default=0, verbose_name='application fee'),
        ),
    ]
