# Generated by Django 4.0.2 on 2023-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_transaction_application_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatistic',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Statistic',
                'verbose_name_plural': 'Sales Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.transaction',),
        ),
        migrations.AddField(
            model_name='productarticle',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether or not the item is shown in the store', verbose_name='is archived'),
        ),
    ]
