# Generated by Django 4.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_transaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_listing',
            field=models.BooleanField(default=False, help_text="Listing categories (farms, stores, etc.) don't require subcategory or price", verbose_name='is listing'),
        ),
        migrations.AlterField(
            model_name='productarticle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productarticle',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory', verbose_name='subcategory'),
        ),
    ]
