# Generated by Django 4.0.2

import django.db.models.deletion
from django.db import migrations, models


def populate_category_from_subcategory(apps, schema_editor):
    ProductArticle = apps.get_model("store", "ProductArticle")
    for product in ProductArticle.objects.filter(
        subcategory__isnull=False, category__isnull=True
    ).select_related("subcategory__category"):
        product.category = product.subcategory.category
        product.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_category_is_listing_alter_productarticle_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productarticle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.category",
                verbose_name="category",
            ),
        ),
        migrations.RunPython(
            populate_category_from_subcategory,
            migrations.RunPython.noop,
        ),
    ]
