name: Continuous Integration and Delivery

on: [push]
        
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    env:
      DO_DOCKER_REGISTRY_NAME: registry.digitalocean.com
      DO_DOCKER_IMAGE_NAME: registry.digitalocean.com/eggslist-container/eggslist-backend
    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Build container image
        run: | 
          docker build -t ${{ env.DO_DOCKER_IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7) .
          docker build -t ${{ env.DO_DOCKER_IMAGE_NAME }}:latest .


      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push ${{ env.DO_DOCKER_IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7)
          docker push ${{ env.DO_DOCKER_IMAGE_NAME }}:latest
